### ISSUE TITLE
Will this library work on Arduino Nano Atmega 328

### ISSUE THREAD

**Issue by ivanplkolev** [AlanChatham/UnoJoy#21]
Hello,
when I try to upload the UnoJoyArduinoSample to my Arduno Nano, 
I get 
Invalid library found in C:\Program Files (x86)\Arduino\libraries\UnoJoy-master: C:\Program Files (x86)\Arduino\libraries\UnoJoy-master
Nowere is written that the library is compatible with Nano, is there a way to run it ?

**Comment by AlanChatham** [comment]
It will not work on the Nano - the Nano uses the FTDI Serial-to-USB chip, whereas UnoJoy relies on being able to reflash the different serial-to-USB chip that's on the Uno and some other boards.
