### ISSUE TITLE
It's possible control six axes with Unojoy?

### ISSUE THREAD

**Issue by Pietrogramma** [AlanChatham/UnoJoy#27]
Hi I'm building some gauges for my home cockpit of te Beech Craft B58 to use with the flight simulator Prepar3d.
I would make the throttle group, that have six indipendent levers, with six potentiometers.
For this reason I would use Unojoy (and not megajoy for space reason) where i would plug the six potentiometer to A0, A1, A2, A3, A4 and A5 pin, it's possible? If yes, can you help me for the code?
Thanks and sorry for bad english.
Regards

**Comment by AlanChatham** [comment]
Hi! You can run the MegaJoy firmware on an Uno just fine, so that's what I would recommend!
