### ISSUE TITLE
Atmel FLIP tool - Is there another location to get it?

### ISSUE THREAD

**Issue by briancavanaugh** [AlanChatham/UnoJoy#28]
Is there another way to download the Atmel FLIP tool?  The provided URL redirects to microchip.com.  I did some searching for this, but I haven't found anything that makes sense for this.  Also, is there an installer for it, or do I simply register it with a command prompt?  I'm using Windows 10.

**Comment by briancavanaugh** [comment]
Actually, I found the place to download it from here....
https://www.microchip.com/developmenttools/ProductDetails/flip
I found this on the official Arduino website, so the link provided in the readme could probably be updated.

**Comment by AlanChatham** [comment]
Thanks! I've updated the link!
