### ISSUE TITLE
Add jstest-gtk to docs as a testing option for Linux users

### ISSUE THREAD

**Issue by samwinslow** [AlanChatham/UnoJoy#42]
[jstest-gtk](http://manpages.ubuntu.com/manpages/bionic/man1/jstest-gtk.1.html) is a simple tool that allows you to visualize button inputs and so on without configuring Processing and Java. Windows may have a built-in utility for this in Device Manager.

I have tested & verified that the out-of-the-box example for the Uno R3 works with this tool!

**Comment by AlanChatham** [comment]
Thanks so much for this! I know that this is super late, but I appreciate you taking the time to add this information, and I'll add it to the project!
