### ISSUE TITLE
Missing ) line 216 Megajoy.h

### ISSUE THREAD

**Issue by pkaser** [AlanChatham/UnoJoy#44]
Missing ) line 216 Megajoy.h

**Comment by mitko-kamburow** [comment]
Hello, 
I looked up the line and there is no missing symbol, have you tried editing that?
The for loop should look like this: 
`    for (int i = 0; i < ANALOG_AXIS_ARRAY_SIZE; i++){
      controllerData.analogAxisArray[i] = 512;
    }
`

**Comment by AlanChatham** [comment]
Just digging back into this project, and wow, embarrassing! Looks like the version of MegaJoy.h in the example code didn't have this, probably hence the confusion. Super appreciate you bringing this up!
