### ISSUE TITLE
How to load TurnIntoAJoystick.bat

### ISSUE THREAD

**Issue by TheGreekGeek201** [AlanChatham/UnoJoy#55]
I keep running the file, but every time I do, an error message shows up as "Cannot find Java Virtual Machine", and when digging deeper, it says that we may have deleted the batchisp file from the ATmega8u2Code folder, when we haven't. Please help.

**Comment by redddcyclone** [comment]
@TheGreekGeek201 You must install the version of Atmel Flip that comes with the JRE 5 included. Had this problem last week.
