### ISSUE TITLE
Arduino/Sparkfun Pro Micro

### ISSUE THREAD

**Issue by zahirkelloud** [AlanChatham/UnoJoy#56]
Any chance this would work on a Pro Micro since it has an Atmega32u4. If yes, what changes should I make to make it work? And should I also flash in the usbserial firmware? I read somewhere that the pro micro already has serial communication.

**Comment by manteka** [comment]
For a Pro Micro you can use Arduino joystick library right out of the box. No need of flashing. Here you have the github project link: https://github.com/MHeironimus/ArduinoJoystickLibrary

**Comment by AlanChatham** [comment]
Thanks, manteka!
